services:
  ca1:
    build: .
    container_name: ca1
    command: ["tail", "-f", "/dev/null"]
    environment:
      - CONFIG_PATH=node_config/node1.json
      - GRPC_PORT=50061
    volumes:
      - .:/app
    ports:
      - "50061:50061"

  ca2:
    build: .
    container_name: ca2
    command: ["tail", "-f", "/dev/null"]
    environment:
      - CONFIG_PATH=node_config/node2.json
      - GRPC_PORT=50062
    volumes:
      - .:/app
    ports:
      - "50062:50062"

  ca3:
    build: .
    container_name: ca3
    command: ["tail", "-f", "/dev/null"]
    environment:
      - CONFIG_PATH=node_config/node3.json
      - GRPC_PORT=50063
    volumes:
      - .:/app
    ports:
      - "50063:50063"

  client:
    build: .
    container_name: client
    command: ["tail", "-f", "/dev/null"]
    environment:
      - NODE_ADDRESSES=ca1:50061,ca2:50062,ca3:50063
      - THRESHOLD=2
    volumes:
      - .:/app
    depends_on:
      - ca1
      - ca2
      - ca3
