# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ca_pb2 as ca__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ca_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CANodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueCertificate = channel.unary_unary(
                '/threshca.CANode/IssueCertificate',
                request_serializer=ca__pb2.CSRRequest.SerializeToString,
                response_deserializer=ca__pb2.CertResponse.FromString,
                _registered_method=True)
        self.SignPartial = channel.unary_unary(
                '/threshca.CANode/SignPartial',
                request_serializer=ca__pb2.NodeSignReq.SerializeToString,
                response_deserializer=ca__pb2.NodeSignResp.FromString,
                _registered_method=True)
        self.SignRevokePartial = channel.unary_unary(
                '/threshca.CANode/SignRevokePartial',
                request_serializer=ca__pb2.RevokeRequest.SerializeToString,
                response_deserializer=ca__pb2.NodeSignResp.FromString,
                _registered_method=True)
        self.ApplyRevocation = channel.unary_unary(
                '/threshca.CANode/ApplyRevocation',
                request_serializer=ca__pb2.RevocationProof.SerializeToString,
                response_deserializer=ca__pb2.RevokeResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/threshca.CANode/Revoke',
                request_serializer=ca__pb2.RevokeRequest.SerializeToString,
                response_deserializer=ca__pb2.RevokeResponse.FromString,
                _registered_method=True)
        self.CRL = channel.unary_unary(
                '/threshca.CANode/CRL',
                request_serializer=ca__pb2.CRLRequest.SerializeToString,
                response_deserializer=ca__pb2.CRLResponse.FromString,
                _registered_method=True)
        self.OCSP = channel.unary_unary(
                '/threshca.CANode/OCSP',
                request_serializer=ca__pb2.OCSPRequest.SerializeToString,
                response_deserializer=ca__pb2.OCSPResponse.FromString,
                _registered_method=True)


class CANodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IssueCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignPartial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignRevokePartial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyRevocation(self, request, context):
        """<-- must match client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CRL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OCSP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CANodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueCertificate,
                    request_deserializer=ca__pb2.CSRRequest.FromString,
                    response_serializer=ca__pb2.CertResponse.SerializeToString,
            ),
            'SignPartial': grpc.unary_unary_rpc_method_handler(
                    servicer.SignPartial,
                    request_deserializer=ca__pb2.NodeSignReq.FromString,
                    response_serializer=ca__pb2.NodeSignResp.SerializeToString,
            ),
            'SignRevokePartial': grpc.unary_unary_rpc_method_handler(
                    servicer.SignRevokePartial,
                    request_deserializer=ca__pb2.RevokeRequest.FromString,
                    response_serializer=ca__pb2.NodeSignResp.SerializeToString,
            ),
            'ApplyRevocation': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyRevocation,
                    request_deserializer=ca__pb2.RevocationProof.FromString,
                    response_serializer=ca__pb2.RevokeResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=ca__pb2.RevokeRequest.FromString,
                    response_serializer=ca__pb2.RevokeResponse.SerializeToString,
            ),
            'CRL': grpc.unary_unary_rpc_method_handler(
                    servicer.CRL,
                    request_deserializer=ca__pb2.CRLRequest.FromString,
                    response_serializer=ca__pb2.CRLResponse.SerializeToString,
            ),
            'OCSP': grpc.unary_unary_rpc_method_handler(
                    servicer.OCSP,
                    request_deserializer=ca__pb2.OCSPRequest.FromString,
                    response_serializer=ca__pb2.OCSPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'threshca.CANode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('threshca.CANode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CANode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IssueCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threshca.CANode/IssueCertificate',
            ca__pb2.CSRRequest.SerializeToString,
            ca__pb2.CertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignPartial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threshca.CANode/SignPartial',
            ca__pb2.NodeSignReq.SerializeToString,
            ca__pb2.NodeSignResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignRevokePartial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threshca.CANode/SignRevokePartial',
            ca__pb2.RevokeRequest.SerializeToString,
            ca__pb2.NodeSignResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyRevocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threshca.CANode/ApplyRevocation',
            ca__pb2.RevocationProof.SerializeToString,
            ca__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threshca.CANode/Revoke',
            ca__pb2.RevokeRequest.SerializeToString,
            ca__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CRL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threshca.CANode/CRL',
            ca__pb2.CRLRequest.SerializeToString,
            ca__pb2.CRLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OCSP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threshca.CANode/OCSP',
            ca__pb2.OCSPRequest.SerializeToString,
            ca__pb2.OCSPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
