# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rdistributedca\"\x1e\n\x0bSignRequest\x12\x0f\n\x07message\x18\x01 \x01(\x0c\">\n\x0cSignResponse\x12\x13\n\x0bshare_index\x18\x01 \x01(\x05\x12\x19\n\x11partial_signature\x18\x02 \x01(\x0c\"\x1d\n\nCRLRequest\x12\x0f\n\x07\x63\x61_name\x18\x01 \x01(\t\"&\n\x0b\x43RLResponse\x12\x17\n\x0frevoked_serials\x18\x01 \x03(\x05\x32\x98\x01\n\rDistributedCA\x12\x46\n\x0bSignMessage\x12\x1a.distributedca.SignRequest\x1a\x1b.distributedca.SignResponse\x12?\n\x06GetCRL\x12\x19.distributedca.CRLRequest\x1a\x1a.distributedca.CRLResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNREQUEST']._serialized_start=32
  _globals['_SIGNREQUEST']._serialized_end=62
  _globals['_SIGNRESPONSE']._serialized_start=64
  _globals['_SIGNRESPONSE']._serialized_end=126
  _globals['_CRLREQUEST']._serialized_start=128
  _globals['_CRLREQUEST']._serialized_end=157
  _globals['_CRLRESPONSE']._serialized_start=159
  _globals['_CRLRESPONSE']._serialized_end=197
  _globals['_DISTRIBUTEDCA']._serialized_start=200
  _globals['_DISTRIBUTEDCA']._serialized_end=352
# @@protoc_insertion_point(module_scope)
