# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DistributedCAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignMessage = channel.unary_unary(
                '/distributedca.DistributedCA/SignMessage',
                request_serializer=service__pb2.SignRequest.SerializeToString,
                response_deserializer=service__pb2.SignResponse.FromString,
                _registered_method=True)
        self.GetCRL = channel.unary_unary(
                '/distributedca.DistributedCA/GetCRL',
                request_serializer=service__pb2.CRLRequest.SerializeToString,
                response_deserializer=service__pb2.CRLResponse.FromString,
                _registered_method=True)


class DistributedCAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCRL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedCAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SignMessage,
                    request_deserializer=service__pb2.SignRequest.FromString,
                    response_serializer=service__pb2.SignResponse.SerializeToString,
            ),
            'GetCRL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCRL,
                    request_deserializer=service__pb2.CRLRequest.FromString,
                    response_serializer=service__pb2.CRLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributedca.DistributedCA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributedca.DistributedCA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DistributedCA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedca.DistributedCA/SignMessage',
            service__pb2.SignRequest.SerializeToString,
            service__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCRL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributedca.DistributedCA/GetCRL',
            service__pb2.CRLRequest.SerializeToString,
            service__pb2.CRLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
